Task2 angular implementation
artsiom-aliakseichyk/ng2-training pull request #2
Opened 2016-12-03 11:15 UTC by artsiom-aliakseichyk

2016-12-03 16:15 UTC, ilyabasiuk requested changes

2016-12-03 16:15 UTC, ilyabasiuk commented on package.json
> +    "start": "webpack-dev-server --progress --colors --inline --open  --watch",
Got errors while running 
http://screencast.com/t/TXtxqd1y
Please fix it. 
Tip: Do we really need both of this types es6-shim and core-js ?

2016-12-03 16:15 UTC, ilyabasiuk commented on README.md
> +npm run
start insread of run?

2016-12-03 16:15 UTC, ilyabasiuk commented on app/components/citylist-paginator-component/citylist-paginator.component.html
> +			let i = index" (click)="setPage($event)"
I'd recomend you to pass page number here instead of $event. It will make you component method code more clear and more testable.

2016-12-03 16:15 UTC, ilyabasiuk commented on app/components/citylist-paginator-component/citylist-paginator.component.ts
> +        let pages = document.querySelectorAll(".city-list-page");
Please do not dom manipalition in component code. Some times it's really, but in 95% od cases you shouldn't do that. 
Instead of it. Pagination component should have Output property, which will pass  selected page number to parent component.

2016-12-03 16:15 UTC, ilyabasiuk commented on app/services/weather-api.service.ts
> +        let pageNum: number = 0;
Weather Api Service should knew anything about pagination.
Please delete this logic from here.

2016-12-03 16:15 UTC, ilyabasiuk commented on app/components/main-component/main.component.ts
> +    cityDetails: cityDetails[][];
Make it simplier just cityDetails[]. It's connected with comment weather service.

2016-12-03 16:15 UTC, ilyabasiuk commented on app/components/main-component/main.component.ts
> +                this.WeatherApi.getWeatherData({
Do unsubscribe in ngOnDestroy to avoid memory leaks.

2016-12-03 16:15 UTC, ilyabasiuk commented on app/components/map-component/map.component.ts
> +    constructor() {}
Is there are any reason to have this empty constuctors? 
I prefer to keep code clean and avoid unnessesary constructions.

2016-12-03 16:15 UTC, ilyabasiuk commented on app/interfaces/interfaces.ts
> +export interface cityDetails extends weatherData {
It's actualy not very good case for using extending. 
To keep CityDeatails simple you could create one more intreface, let's say MainDetails 

interface MainDetails {
                temp: number;
  		humidity: number;		  		
  		pressure: number;		  		
  		temp_max: number;		  		
  		temp_min: number;
}

and then use it in CityDetails 
interface CityDetails {
....
main: MainDetails
....
 }

2016-12-03 16:15 UTC, ilyabasiuk commented on app/app.component.ts
> +    encapsulation: ViewEncapsulation.None
Never use it) 
I know that in our lection it was mentions as most preferrable case, but it's a mistake. 

One of the most intresting things in angular 2 - it style encapsualtion and we should use. 
I agree that we some times need styles, wich will be available around hole application. 
For examle grids, or main colors or etc. I that case I'd probably agree with using encapsulation none, but actuallly even in that case I'd preffer to include it in app as separate file.

2016-12-04 15:25 UTC, artsiom-aliakseichyk commented on app/app.component.ts
> +    encapsulation: ViewEncapsulation.None
Will leave this for global styles (html, body)

2016-12-06 07:31 UTC, merged